added p2_conditions_options_layer
xch-dev/chia-wallet-sdk pull request #130
Opened 2024-11-25 23:52 UTC by cameroncooper

Working on adding options contracts. WIP.

2024-11-25 23:53 UTC, Rigidity approved these changes

2024-11-25 23:53 UTC, Rigidity requested changes
lgtm soon™️

2024-11-25 23:57 UTC, cameroncooper commented
The general idea with options is you have some coin that is locked up and can be spent 2 ways:

Before timestamp X it can be traded for Y as long as the contract NFT is sent to the burn address. This is executing the contract.

After timestamp X it can be spent to a puzzle hash predetermined by the maker. This is taking back funds from an expired contract.

2025-03-14 23:38 UTC, Rigidity commented
Closing for now, in favor of the new implementation - CHIP is here https://github.com/Chia-Network/chips/pull/152

2025-03-14 23:38 UTC, closed without merging